"""
sentinel/core/claude_client.py
================================
Single entry point for all Claude API communication.

FROZEN MODULE:
    This file is written once on Day 1 and never modified.
    All API call configuration lives here.
    If you need different behaviour, pass parameters —
    do not edit this file.

DESIGN DECISIONS:

    1. Factory function, not module-level singleton:
       get_client() creates a new client each call.
       This makes testing easy — mock get_client(), not
       a global object.

    2. Single create_message() function:
       Every agent, every day, every tool call goes through
       this one function. Logging, retry logic, and model
       switching all happen in one place.

    3. tool_choice parameter documented explicitly:
       This is the most exam-tested parameter in Domain 1+2.
       The inline comments are intentional learning material.

EXAM NOTE — tool_choice values:
    "auto"                          → Claude decides whether to call
                                      a tool or respond in text.
                                      Default behaviour.

    "any"                           → Claude MUST call a tool.
                                      Picks which one itself.
                                      Use when you need guaranteed
                                      structured output.

    {"type": "tool", "name": "X"}  → Claude MUST call tool X.
                                      Use to force a specific tool
                                      as the first action (e.g.,
                                      always verify identity first).
"""

import anthropic
from sentinel.config.settings import settings


def get_client() -> anthropic.Anthropic:
    """
    Create and return a configured Anthropic client.

    Called fresh each time rather than cached at module level
    so tests can mock it without patching global state.
    """
    return anthropic.Anthropic(api_key=settings.anthropic_api_key)


def create_message(
    messages: list[dict],
    tools: list[dict] | None = None,
    system: str | None = None,
    tool_choice: dict | str | None = None,
) -> anthropic.types.Message:
    """
    Make a single call to the Claude API.

    Args:
        messages:    Full conversation history in Anthropic format.
                     MUST include all prior turns — Claude has no
                     memory between calls.

        tools:       Tool definitions Claude can call.
                     Each entry: {name, description, input_schema}
                     Rich descriptions = reliable tool selection.

        system:      System prompt defining the agent's role.
                     Set once per conversation, not per message.

        tool_choice: Controls whether/which tools Claude calls.
                     See module docstring for all three options.

    Returns:
        Raw anthropic.types.Message — caller inspects stop_reason.

    EXAM NOTE:
        This function does NOT loop. It makes exactly ONE API call.
        The agentic_loop.py is responsible for calling this
        repeatedly until stop_reason == "end_turn".
    """
    client = get_client()

    kwargs: dict = {
        "model": settings.claude_model,
        "max_tokens": settings.max_tokens,
        "messages": messages,
    }

    if system:
        kwargs["system"] = system

    if tools:
        kwargs["tools"] = tools

    if tool_choice:
        kwargs["tool_choice"] = tool_choice

    return client.messages.create(**kwargs)